name: site-build-push

on:
  # for local PR builds esp. builds in forked repositories
  push:
    branches:
      - main

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.head_commit.sha}}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install Dependencies
        run: npm ci

      # avoid hard-coding pages url in workflow => use github API to retrieve deployment website url (see https://stackoverflow.com/a/76354104/29917717)
      - name: Get pages deployment URL
        run: |
          pages_url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          url=$(echo $pages_url|cut -d'/' -f 1)//$(echo $pages_url|cut -d'/' -f 3)
          base_url=$(echo $pages_url|cut -d'/' -f 4)
          echo "url=$url" >> "$GITHUB_ENV"
          echo "base_url=$base_url" >> "$GITHUB_ENV"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Patch docusaurus.config.js
        run: |
          sed -E -i "s^url:(..*)^url: '${{ env.url }}',^g" docusaurus.config.js
          sed -E -i "s^baseUrl:(..*)^baseUrl: '/${{ env.base_url }}',^g" docusaurus.config.js

      - name: Verify Patch Application
        run: cat docusaurus.config.js

      - name: Build Website
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.head_commit.sha}}

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          path: build/

      - name: Set up Git
        env:
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER: ${{ secrets.GIT_USER }}
        run: |
          git config --global user.email "$$GIT_USER_EMAIL"
          git config --global user.name "$$GIT_USER"

      # avoid hard-coding pages url in workflow => use github API to retrieve deployment website url (see https://stackoverflow.com/a/76354104/29917717 + https://docs.github.com/en/rest/pages/pages?apiVersion=2022-11-28#get-a-github-pages-site)
      - name: Switch to GitHub Pages Branch
        run: |
          gh_pages_branch=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.source.branch')
          git fetch origin $gh_pages_branch
          git checkout $gh_pages_branch
          echo "gh_pages_branch=$gh_pages_branch" >> "$GITHUB_ENV"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: github.ref == 'refs/heads/main'
        run: |
          shopt -s extglob
          rm -rf !(@*)

      - name: Move Build Files
        run: |
          if [[ -d "build" && "$(ls -A build)" ]]; then
            if [[ "${{ github.event.pull_request.head.ref }}" != "refs/heads/main" ]]; then
              mv build/* @${{ github.event.pull_request.head.ref }}/
              cd @${{ github.event.pull_request.head.ref }}/
            else
              mv build/* ./
            fi
            tar -xvf github-pages/artifact.tar
            rm github-pages/artifact.tar
          else
            echo "No build files found. Skipping move step."
          fi

      - name: Commit and Push Changes
        run: |
          git add -A
          git commit --amend --no-edit || echo "No changes to commit"
          git push -f origin ${{ env.gh_pages_branch }}